/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Tenant as PrismaTenant } from "@prisma/client";

export class TenantServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.TenantCountArgs, "select">): Promise<number> {
    return this.prisma.tenant.count(args);
  }

  async tenants<T extends Prisma.TenantFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.TenantFindManyArgs>
  ): Promise<PrismaTenant[]> {
    return this.prisma.tenant.findMany<Prisma.TenantFindManyArgs>(args);
  }
  async tenant<T extends Prisma.TenantFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.TenantFindUniqueArgs>
  ): Promise<PrismaTenant | null> {
    return this.prisma.tenant.findUnique(args);
  }
  async createTenant<T extends Prisma.TenantCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TenantCreateArgs>
  ): Promise<PrismaTenant> {
    return this.prisma.tenant.create<T>(args);
  }
  async updateTenant<T extends Prisma.TenantUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TenantUpdateArgs>
  ): Promise<PrismaTenant> {
    return this.prisma.tenant.update<T>(args);
  }
  async deleteTenant<T extends Prisma.TenantDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.TenantDeleteArgs>
  ): Promise<PrismaTenant> {
    return this.prisma.tenant.delete(args);
  }
}
